--
-- Script was generated by Devart dbForge Studio for SQL Server, Version 6.6.5.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 9/6/2024 7:49:17 PM
-- Server version: 16.00.1000
-- Please backup your database before running this script
--

USE master
GO

--
-- Add filegroup tableFG to database HIS
--
ALTER DATABASE HIS
  ADD FILEGROUP tableFG
GO

--
-- Add filegroup indexFG to database HIS
--
ALTER DATABASE HIS
  ADD FILEGROUP indexFG
GO

--
-- Add file tableFile to database HIS
--
ALTER DATABASE HIS
  ADD FILE
(
    NAME = N'tableFile',
    FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLSERVER2022\MSSQL\DATA\tableFile.ndf',
    SIZE = 524288KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 524288KB
)
TO FILEGROUP tableFG
GO

--
-- Add file indexFIle to database HIS
--
ALTER DATABASE HIS
  ADD FILE
(
    NAME = N'indexFIle',
    FILENAME = N'D:\sql\HIS database\indexFIle.ndf',
    SIZE = 524288KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 524288KB
)
TO FILEGROUP indexFG
GO

ALTER DATABASE HIS MODIFY FILEGROUP tableFG DEFAULT